### ISSUE TITLE
Directive invocation argument value is empty when it's an Input

### ISSUE THREAD

**Issue by greabock** [railt/railt#87] opened 2018-01-14 15:21 UTC
- Compiler Version: 1.1.1
- PHP Version: 7.1
- Component: SDL

### Description:
When we typing directive argument as an `Input` and then invoke this directive with argument correct struct value of passed argument of directive invocation is actualy empty object.

### Steps To Reproduce:
Compile this:
```elm
directive @some(value: Bar) on OBJECT

input Bar {
   one: String!
   two: String
}

type Foo @some(value: {one: "Hey!"}){
    any: String!
}
```
then
```php
$value = $document
    ->getTypeDefinition('Foo')
    ->getDirective('some')
    ->getPassedArgument('value')
;

var_dump($value);
```
### Expected result:
Instance of `InputInvocationBuilder`  filled with actual value (`{one: "Hey!"}`).

### What happens instead?
Empty Instance of `InputInvocationBuilder`:
```
object(Railt\SDL\Reflection\Builder\Invocations\InputInvocationBuilder)#699 (0) {}
```

**Comment by greabock** [comment] 2018-01-14 15:24
Probably related with #86

**Comment by SerafimArts** [comment] 2018-01-16 09:43
> Probably related with #86

Nope. There were two problems:
1) The problem is that the selection of types from the "future" stack (this is stack of invocable types) was not recursive (that is, if type A adds a type B to the stack during the build of dependencies - it does not build). In this connection, the meaning of the input (which is the Invocation) inside the directive (which is also an Invocation) is not compiled.
2) In addition, the dependency graph between call and type definition during the resolves of this type was incorrectly built.

https://github.com/railt/railt/commit/44caa0737dd3b3bf4ffeb7087e675b1596944bcf

**Comment by SerafimArts** [comment] 2018-01-16 09:44
Fixed: https://github.com/railt/railt/commit/44caa0737dd3b3bf4ffeb7087e675b1596944bcf https://github.com/railt/railt/commit/2abc815dfd64256e55b3eb447fbb08e770fcd89a and https://github.com/railt/railt/commit/82f65e1e8eae36c88cdbf1e875cc03ee20553556

Will be in the next release.

**Closed by SerafimArts** 2018-01-16 09:44 UTC
Labels: Bug, RL/SDL
